name: Makefile Slides CI

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build-presentation:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4

    - name: Build slides
      uses: xu-cheng/latex-action@v3
      with:
        texlive_version: 2025
        root_file: isdm25.tex

    - name: Publish artifacts PDFs
      uses: actions/upload-artifact@v4
      with:
        name: isdm25
        path: isdm25.pdf

  release:
    name: Create/Update Release
    runs-on: ubuntu-latest
    needs: build-presentation
    steps:
    - name: Download slides artifact
      uses: actions/download-artifact@v4
      with:
        name: isdm25
        path: ./artifacts

    - name: Create or update GitHub release and upload slides
      uses: ncipollo/release-action@v1
      with:
        tag: isdm25-slides-latest
        name: ISDM'25 Slides (automated)
        artifacts: ./artifacts/isdm25.pdf
        allowUpdates: true
